#include "../include/std_lib_facilities.h"

int solution(const string& s) {
	if (s.size() == 0) return 0;
	int sz = s.size();
	int val = 1;
	for (int i = 1; i < sz; i++) {
		unordered_map<char, int> m;
		int tmp = 0;
		for (int j = i; j >= 0; j--) {
			if (m[s[j]] == 0) {
				tmp++;
				m[s[j]] = 1;
			}
			val += tmp;
		}
	}
	return val;
}
int main() {
	cout << solution("aasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdankjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdankjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdankjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdankjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdankjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdankjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdankjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasdaaasdsdssdasdwqeqesadasdhashdkjasnbcjkhaishdioahdjkasnkjdhashdjanckjzxnicuhzxkjcbzxjciuahudhasqwedasda");
}